function A07_PlotsTab
global MainFigure
global Strct_MainFigure
global PltTryTab
global Robot

Strct_MainFigure.Panel_PlotsTab=uipanel('Parent',MainFigure,'Units','Normalized','position',[0.01 0.01 0.98 0.91],...
    'visible','on');

PltTryTab.Panel_PC_Robot=uipanel('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.4 0.85 0.13 0.14],...
    'Title','PC/Robot','titleposition','centertop');
PltTryTab.BttnGrp_PC_Robot=uibuttongroup('Parent',PltTryTab.Panel_PC_Robot,'units','normalized','position',[0.01 0.01 0.98 0.98],...
    'bordertype','none','SelectionChangeFcn','F_PltTryTab_BtttnGrp_PCRbt');
PltTryTab.RdBttn_PC=uicontrol('Parent',PltTryTab.BttnGrp_PC_Robot,'units','normalized','position',[0.1 0.6 0.7 0.35],...
    'style','RadioButton','String','PC','Value',1);
PltTryTab.RdBttn_Rbt=uicontrol('Parent',PltTryTab.BttnGrp_PC_Robot,'units','normalized','position',[0.1 0.1 0.7 0.35],...
    'style','RadioButton','String','Robot');

PltTryTab.Panel_Step_Walk=uipanel('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.8 0.85 0.18 0.14],...
    'Title','Step/Walk','titleposition','centertop');
PltTryTab.Txt_StNmbr=uicontrol('Parent',PltTryTab.Panel_Step_Walk,'units','normalized','position',[0.01 0.7 0.45 0.4],...
    'style','Text','String','Tipo:');
PltTryTab.PpUp_TipoPaso=uicontrol('Parent',PltTryTab.Panel_Step_Walk,'units','normalized','position',[0.01 0.6 0.45 0.05],...
    'style','PopUpMenu','Value',2,'callback','F_PltTryTab_PpUp_TipoPaso',...
    'String',{'Step','Walk'});
PltTryTab.Txt_StNmbr=uicontrol('Parent',PltTryTab.Panel_Step_Walk,'units','normalized','position',[0.5 0.7 0.45 0.4],...
    'style','Text','String','Step Number:');
PltTryTab.PpUp_Paso=uicontrol('Parent',PltTryTab.Panel_Step_Walk,'units','normalized','position',[0.55 0.6 0.4 0.05],...
    'style','PopUpMenu','String',{''},'enable','off');

PltTryTab.Panel_Element=uipanel('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.54 0.85 0.25 0.14],...
    'Title','Trayectory','titleposition','centertop');

PltTryTab.Txt_StNmbr=uicontrol('Parent',PltTryTab.Panel_Element,'units','normalized','position',[0.05 0.8 0.4 0.3],...
    'style','Text','String','Values:');
PltTryTab.PpUp_Grupo=uicontrol('Parent',PltTryTab.Panel_Element,'units','normalized','position',[0.05 0.6 0.45 0.05],...
    'style','PopUpMenu','Value',2,'callback','F_PltTryTab_PpUp_Grupo',...
    'String',{'Time','Angles','Coord. Pelvis','Coord. Right Foot','Coord. Left Foot.'});
PltTryTab.Txt_StNmbr=uicontrol('Parent',PltTryTab.Panel_Element,'units','normalized','position',[0.6 0.8 0.4 0.3],...
    'style','Text','String','Trayectory:');
for i=1:18
    ElemntStr{i}=['Th' num2str(i)];
end
PltTryTab.PpUp_Elemento=uicontrol('Parent',PltTryTab.Panel_Element,'units','normalized','position',[0.7 0.6 0.25 0.05],...
    'style','PopUpMenu','String',ElemntStr,'Value',9);

PltTryTab.RdBttn_Add=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.5 0.8 0.16 0.05],...
    'style','RadioButton','String','Añadir Trayectoria');
PltTryTab.PshBttn_Plot=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.64 0.78 0.07 0.06],'Style','PushButton',...
    'String','Plot','callback','F_PltTryTab_PshBttn_PlotTry');
PltTryTab.PshBttn_Clear=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.72 0.78 0.07 0.06],'Style','PushButton',...
    'String','Clear','callback','F_PltTryTab_PshBttn_Clear');

PltTryTab.RdBttn_Grid=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.8 0.8 0.08 0.05],...
    'style','RadioButton','String','grid','Value',0,'callback','F_PltTryTab_RdBttn_Grid');

PltTryTab.RdBttn_Time=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.85 0.8 0.08 0.05],...
    'style','RadioButton','String','Step Time','Value',0,'callback','F_PltTryTab_RdBttn_Time');

%Panel del Plot
PltTryTab.Panel_PlotTry=uipanel('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.4 0.07 0.58 0.69],'Title',...
    'Trayectories','TitlePosition',' centertop','CreateFcn',''); 
PltTryTab.axis=axes('Parent',PltTryTab.Panel_PlotTry);

%Play Motion
%%------------------------------------------------------------------------
PltTryTab.TggleBttn_PlayAnimation=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.02 0.915 0.07 00.05],'Style','ToggleButton',...
    'String','Play','callback','E_WlkTab_TggleBttn_PlayAnim(gcbo)');
PltTryTab.Slider_TimePlayAnimation=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.02 0.87 0.31 0.025],'Style','slider',...
    'min',0,'max',1,'Callback','global StepForChange; E_WlkTab_Sldr_PlayAnim(gcbo)');
PltTryTab.Edit_TimePlayAnimation=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.34 0.87 0.04 0.05],'Style','Edit');
PltTryTab.Text_TimePlayAnimation=uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.09 0.92 0.07 0.03],'Style',...
    'text','String','Accelerate:');
PltTryTab.PpupMenu_Acelerar= uicontrol('Parent',Strct_MainFigure.Panel_PlotsTab, 'Style','popupmenu','Units','Normalized','Position',[0.16 0.94 0.06 0.02],...
    'String',{'01','02','05','10'},'Enable','on','FontWeight','bold','Callback', 'E_WlkTab_Ppup_Acel');
%%------------------------------------------------------------------------

%Botones para la vista
PltTryTab.uiBttnGrp_ViewsWlk=uibuttongroup('Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.02 0.02 0.35 0.045],...
    'SelectionChangeFcn','E_WlkTab_BttnGrp_ViewsWlk','BorderType','none');
PltTryTab.uiRdBttn_Lat = uicontrol('Parent',PltTryTab.uiBttnGrp_ViewsWlk,'Style','Radio','String','Lateral',... 
                                    'units','normalized','Position',[0.01 0.01 0.2 0.9],'TooltipString','Lateral View','Value',0);
PltTryTab.uiRdBttn_Prsv = uicontrol('Parent',PltTryTab.uiBttnGrp_ViewsWlk,'Style','Radio','String','Perspectiva',... 
                                    'units','normalized','Position',[0.23 0.01 0.29 0.9],'TooltipString','Perspective View','Value',1);
PltTryTab.uiRdBttn_Frnt = uicontrol('Parent',PltTryTab.uiBttnGrp_ViewsWlk,'Style','Radio','String','Front',... 
                                    'units','normalized','Position',[0.55 0.01 0.2 0.9],'TooltipString','Front View','Value',0);
PltTryTab.uiRdBttn_Up = uicontrol('Parent',PltTryTab.uiBttnGrp_ViewsWlk,'Style','Radio','String','Upper',... 
                                    'units','normalized','Position',[0.74 0.01 0.2 0.9],'TooltipString','Upper view','Value',0);
%Panel del Plot
%%------------------------------------------------------------------------
PltTryTab.Panel_PlotIK=uipanel(   'Parent',Strct_MainFigure.Panel_PlotsTab,'units','normalized','position',[0.02 0.07 0.37 0.8],'Title',...
    'Direct Kinematics','TitlePosition',' centertop'); 
PltTryTab.Axes=axes('parent',PltTryTab.Panel_PlotIK);

grid on
axis equal
axis(Robot.Axis);
view(59,27);
set(PltTryTab.Axes,'CameraViewAngle',7);
xlabel('x');
ylabel('y');
zlabel('z');
hold on

PlotBLD_Wlk(PltTryTab.Axes)