function R=EulYXZ_2_Rot(phi,th,psi)

R=[ cos(phi)*cos(psi) + sin(phi)*sin(psi)*sin(th),  cos(psi)*sin(phi)*sin(th) - cos(phi)*sin(psi), cos(th)*sin(phi);...
                                 cos(th)*sin(psi),                               cos(psi)*cos(th),         -sin(th);...
    cos(phi)*sin(psi)*sin(th) - cos(psi)*sin(phi),  sin(phi)*sin(psi) + cos(phi)*cos(psi)*sin(th), cos(phi)*cos(th)];