function G01_Message_Nao()
global Cnnct

String={'\bf{Conexión a Nao:}',' ','\rm  Asegurese tener acceso a la conexión internet de NAO',...
    'y conocer la IP del robot'};

Figure1=dialog('Name','Connect to Bioloid','MenuBar','none','Toolbar','none','units','normalized',...
    'OuterPosition',[0.4 , 0.4, 0.3, 0.25]);
uibutton('Parent',Figure1, 'Style','text','units','normalized', 'Position',[0.2 0.55 0.6 0.6],...
    'String',String,'HorizontalAlignment','center');
uicontrol('Parent',Figure1, 'Style','text','units','normalized', 'Position',[0.09 0.36 0.4 0.12],...
    'String','Introduzca la dirección IP:','Fontsize',10);
Cnnct.NaoIPEdit=uicontrol('Parent',Figure1, 'Style','edit','units','normalized', 'Position',[0.5 0.37 0.4 0.12],...
    'BackGroundColor','w','Fontsize',10,'String','192.168.1.107');
uicontrol('Parent',Figure1, 'Style','pushbutton','units','normalized', 'Position',[0.4 0.08 0.2 0.15],...
    'Callback', 'global Cnnct; Cnnct.NaoIP=get(Cnnct.NaoIPEdit,''String''); closereq; G02_NaoCnnct','String','OK','HorizontalAlignment','center','Fontsize',10);


